---
title: "Assignment 6"
author: "ZACHARIAH ALEX"
date: "2022-11-20"
output:
  pdf_document: default
  html_document: default
---



$$\text{Formulating lp model problem}$$

$$\text{ Objective function: }$$

Minimize Z : 775x1 + 800x2 + 800x3 + 800x4 + 800x5 + 775x6 + 750x7

$$\text{Constraints}$$ 
$$0x1 + x2 + x3 + x4 + x5 + x6 + 0x7 >= 18$$
$$0x1 + 0x2 + x3 + x4 + x5 + x6 + x7 >= 27$$
$$x1 + 0x2 + 0x3 + x4 + x5 + x6 + x7 >= 22$$
$$x1 + x2 + 0x3 + 0x4 + x5 + x6 + x7 >= 26$$
$$x1 + x2 + x3 + 0x4 + 0x5 + x6 + x7 >= 25$$
$$x1 + x2 + x3 + x4 + 0x5 + 0x6 + x7 >= 21$$
$$x1 + x2 + x3 + x4 + x5 + 0x6 + 0x7 >= 19$$

$$\text{for all}$$
$$x1, x2 ,x3 ,x4 ,x5 ,x6 ,x7  >= 0$$



```{r}

#Reading lp file 

library(lpSolveAPI)
shipdata<- read.lp("AP-Shipping.lp")
shipdata

```

$$\text{Solving the lp model to find optimal numnber of workers}$$

```{r}
solve(shipdata)
get.objective(shipdata)
get.variables(shipdata)

```
*Objective function =25675 ie. Total cost of labours*

```{r}
workers<- matrix(c(0,4,5,0,8,1,0,0,0,5,0,8,1,13,2,0,0,0,8,1,13,2,4,0,0,8,1,13,2,4,5,0,0,1,13,2,3,4,0,0,0,13,2,4,5,0,8,0,0), ncol=7,byrow=TRUE)

row.names(workers) <- c('Sun','Mon','Tues','Wed','Thur','Fri','Sat')

colnames(workers)<- c('Sun/Mon','Mon/Tues','Tues/Wed','Wed/Thur','Thur/Fri','Fri/Sat','Sat/Sun')

workers

```
*Workers should be assigned with given number of shifts in the factory in a week to minimize the total labor expenses*

```{r}
rowSums(workers)

```

*Number of workers required according to the scheduled shift for each day to minimize the total labor wage expenses*
